
# localhost:8761/eureka

#Default port no for EurekaServer
server:
  port: 8761

# EurekaServer can also act as EurekaClient
# To avoid this Server to act as Client
eureka:
  client:
    register-with-eureka: false
    
    # Should not use the resources (registry) himself
    fetch-registry: false
  
