

spring:
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/capstone
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: M_y_$q1_
  jpa:
    hibernate:
      ddl-auto: update

#To name the client
  application:
    name: WalletUser


server:
  port: 9292



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    
    #Location of the Server
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
  # Location where the instance of client will be running
  instance:
    hostname: localhost
